###############################################################################
# Sloan Digital Sky Survey (SDSS)
# IDL support code for products: idlmapper, idlspec2d
#
# S. Burles & D. Schlegel
###############################################################################

SHELL = /bin/sh
#
all :;

#
# Install things in their proper places in $(DJS_DIR)
#
install :
	- cp *.so $(DJS_DIR)/lib

clean :
	- /bin/rm -f *~ core *.so



