###############################################################################
# Sloan Digital Sky Survey (SDSS)
# IDL support code for products: idlmapper, idlspec2d
#
# S. Burles & D. Schlegel
# edited by D. Finkbeiner 18 Feb 2002
###############################################################################

#
# Invoke Make in each subdirectory under $DEEP_DIR
#
SHELL = /bin/sh

all :;

clean :;
